### ISSUE TITLE
Record ID not generated for 1st form

### ISSUE THREAD

**Issue by mdidish** [lsgs/redcap-record-autonumbering#14]
First thank you for your external module, which allows us to personalize record id. However, we have a bug and a question.

The bug:
- I have two forms, and the second form displays information from fields of the first form (first and last name initials, sex, etc.)
- if I completely fill out the first form, when I go to the second form with the "Save an Next Form" button, informations from the first form are not displayed on this second form.
- after validating this second form, when I display all records, I find two records: one with only the 1st form, and another with only the 2nd form.
- on the other hand, if I do not fill in a required field on the first form, when I click on the Next Form button, I have a warning message, and when I arrive on the second form, I have the record Id, and the data from the first form are also displayed, so I only get one record with both forms filled out.

The question:
- Usually when I create a new record, I see the list of forms, and I have to click on the first form to display it.
- With your module activated, the first form is displayed directly when I create a new recor, which I prefer.
-Do you know if it is possible to have this behavior without your module?

Thank you
Marc

**Comment by lsgs** [comment]
Thank you for your interest in the module Marc.

For the bug, are you able to provide a minimal XML so I can have a go at replicating it? I've tried in some of my existing projects with no luck.

You ask if it is possible to have the skipping of the empty Record Home page be default behaviour without this module. Well, it is not REDCap's default behaviour so you it will always requre something to insert the customisation. 
* It can be done using the JavaScript Injector external module to change the behaviour of the "+ Add New Record" button on Add/Edit Record and Dashboard pages.
* It can also be done for regular autonumbering via this module!

**Comment by mdidish** [comment]
Hi
Thank you for your reponse. I no longer have access to this project, I will let you know if I will have it again in the future.
Best,
Marc

**Comment by lsgs** [comment]
No worries Marc. Raise another issue if you have any more problems with the module.
