### ISSUE TITLE
Error in download

### ISSUE THREAD

**Issue by GitIt2Go** [lsgs/redcap-record-autonumbering#15]
When downloading from REDCap Control Center, REDCap Repo, I get:
  
REDCap crashed due to an unexpected PHP fatal error!

Error message: Uncaught Exception: The request to retrieve the name for module 1233 from the repo failed: . in redcap_v12.0.9/ExternalModules/classes/ExternalModules.php:4619 Stack trace: #0 redcap_v12.0.9/ExternalModules/manager/ajax/download-module.php(6): ExternalModules\ExternalModules::downloadModule(1233, false, true) #1 {main} thrown
File: redcap_v12.0.9/ExternalModules/classes/ExternalModules.php
Line: 4619

Any help appreciated.

**Comment by lsgs** [comment]
I can't replicate this problem. Have you experienced it with other external modules @GitIt2Go? I've just released v1.0.5 of this module so try in a day or two when that has been approved and see if the problem is still present.
