### ISSUE TITLE
Possible to generate "batched" record ID's based on birthyear or custom data field?

### ISSUE THREAD

**Issue by BdR76** [lsgs/redcap-record-autonumbering#17]
This external module looks very interesting. The default out-of-the-box options are either auto-numbering starting from 1 or manually enter every record ID, which is quite limited imho.

I was wondering if it's possible to generate record ID's based on a custom data field, like a birthyear, sex, randomisation group (I, II, III) or something like that?

Currently we have a study that works with cohorts of newborns, and we're migrating from another system to REDCap. In the old system, each new patient number is based on the birthdate plus an autonumber sequence, see examples below

```
Birthdate   recordID
20-01-2020  2020-001
29-01-2021  2021-001
19-02-2021  2021-002
21-02-2021  2021-003
18-02-2020  2020-002
14-03-2021  2021-004
02-03-2020  2020-003
21-03-2021  2021-005
```

Is something  like this possible? afaik something like that can't be done using the current options in this external module, is that correct (maybe I'm missing something)?

Btw technically this might be feasible by using an Dynamic Query (SQL) field maybe. I mean, I am able to construct an SQL statement in REDcap that yields the desired patient number.

**Comment by lsgs** [comment]
Sorry to be late to this @BdR76. The existing auto-number generators don't include one that enables the use of data entered in form fields within the generated record ids. It is feasible - indeed I have done it for one project - but it is not a quick job to do it in a neat, generic way.

Implementing this scheme with the existing functionality could only be done if you created a new DAG for each year and used the "increment within DAG" option. (You would not need to assign your users to a year/DAG). If you have existing DAGs then you would need to move to DAG per site/year.
