### ISSUE TITLE
Your tags and commit messages contradict one another

### ISSUE THREAD

**Issue by pbchase** [lsgs/redcap-record-autonumbering#4]
@lsgs, your tags and commit messages contradict one another. Do you think you could make them agree going forward? We are making up version numbers as we deploy your software. It's very confusing for us because they don't align with yours.

FYI, we have used commit 5d8a57d in production for a very long time and are happy with it. The downside is the cosmetic error message that you apparently fixed in 2d509f8. We're going to test 2d509f8 here soon.

**Comment by lsgs** [comment]
Sorry @pbchase. I've done another so I hope it's clearer this time!
