### ISSUE TITLE
Use of __construct causes module to turn on Auto-numbering for ALL projects in certain versions of REDCap

### ISSUE THREAD

**Issue by ChemiKyle** [lsgs/redcap-record-autonumbering#5]
This bug appears in REDCap 10.5.1 but not in 10.3.3 or earlier

The module causes projects to be unable to disable "Auto-numbering for records", even if the module is never enabled for that project. This is because `__construct()` runs on every page with no regard to the module's activation status.

To recreate:

1. Enable the module at the system level and **do not** set "Enable module on all projects by default"
1. Create any project (any template is fine)
1. Go to project setup and disable "Auto-numbering for records" under Optional
1. Reload the page
1. Observe that Auto-numbering is enabled

**Comment by lsgs** [comment]
Closed by [PR#6](https://github.com/lsgs/redcap-record-autonumbering/pull/6)
