### ISSUE TITLE
Project level configuration contradiction: Specify a fixed prefix (can be blank)

### ISSUE THREAD

**Issue by ChemiKyle** [lsgs/redcap-record-autonumbering#8]
In the Project level EM config, when using Record auto-numbering option "Padded integer increment with prefix", the field "Specify a fixed prefix (can be blank)" is misleading. Leaving this blank throws an alert:

https://github.com/lsgs/redcap-record-autonumbering/blob/9e956e0ce3aed6007ee401e84e5d82dc71c324c3/AutonumberGenerators/PrefixAndPad.php#L28-L30

I'm not sure what your intent with this option is, but in its current state the field is "soft" required with a popup any time the config page is loaded.

**Comment by lsgs** [comment]
Thanks @ChemiKyle. I committed a fix that enables the prefix to be blank. It's not really a pattern I'd recommend to anyone, but it enables a numbering scheme like 001, 002, 003, ...
